name: PlatformIO CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build (uno_r4_wifi)
        run: pio run -e uno_r4_wifi

      - name: Run native unit tests
        run: pio test -e native

      - name: Show firmware size
        run: pio run -e uno_r4_wifi --target size

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            .pio/build/uno_r4_wifi/*.elf
            .pio/build/uno_r4_wifi/*.bin
            .pio/build/uno_r4_wifi/*.hex

      - name: Run cppcheck (static analysis)
        run: |
          pip install cppcheck
          cppcheck --enable=all --inconclusive --std=c++17 --quiet --suppress=missingIncludeSystem src/
